format:
  revealjs:
    theme: simple
    slide-number: true
    incremental: false
    code-fold: false
    highlight-style: github
    transition: slide
    footer: "Graduate Summer Institute of Epidemiology and Biostatistics"
    logo: "https://www.jhu.edu/assets/themes/shared/src/assets/images/favicons/favicon-96x96.png"
    self-contained: true
    css: ../styles.css
execute:
  echo: true
  message: true
  warning: false

editor:
  render-on-save: true 